version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm uninstall -g cdk
      - npm install -g aws-cdk@1.57.0 typescript
      - npm i
  build:
    commands:
      - cdk synth cicd
  post_build:
    commands:
      - >-
        aws cloudformation validate-template --template-body
        file://cdk.out/cicd.template.json
artifacts:
  files:
    - cdk.out/cicd.template.json
