version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Make sure AWS CDK and TypeScript are installed...
      - npm install -g aws-cdk
      - npm install -g typescript
      - echo Installing CDK application...
      - npm install
  build:
    commands:
      - echo Build started `date`
      - echo Synthesizing AWS CloudFormation template...
      - cdk synth quickstart --parameters IdeStackTemplateURL=$IDE_STACK_TEMPLATE_URL
  post_build:
    commands:
      - echo Build finished `date`
      - echo Validating AWS CloudFormation template...
      - >-
        aws cloudformation validate-template --template-body
        file://cdk.out/quickstart.template.json
artifacts:
  files:
    - cdk.out/quickstart.template.json
