version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm uninstall -g cdk
      - npm install -g aws-cdk@1.57.0 typescript
  pre_build:
    commands:
      - npm install
      - date > /usr/local/lib/node_modules/crpm/.agreed
  build:
    commands:
      - npm run build
      - cdk synth cicd
  post_build:
    commands:
      - >-
        aws cloudformation validate-template --template-body
        file://cdk.out/cicd.template.json
artifacts:
  files:
    - cdk.out/cicd.template.json
