version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm uninstall -g cdk
      - npm install -g aws-cdk@1.30.0 crpm@1.5.1
  pre_build:
    commands:
      - npm install
      - date > /usr/local/lib/node_modules/crpm/.agreed
  build:
    commands:
      - npm run build
      - crpm synth infra/developer-tools/codepipeline/pipeline
  post_build:
    commands:
      - >-
        aws cloudformation validate-template --template-body
        file://infra/developer-tools/codepipeline/pipeline/stack.template.json
artifacts:
  files:
    - infra/developer-tools/codepipeline/pipeline/stack.template.json
